name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  supabase_auth_ui: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  supabase_lints: ^0.1.0

flutter:
  uses-material-design: true
